openapi: 3.1.0
info:
  title: Handläggning API
  version: 1.0.0
  description: API för att hantera handläggningar och yrkanden.

paths:
  /handlaggning/{handlaggningId}:
    get:
      tags: [ HandlaggningController ]
      operationId: getHandlaggning
      summary: Hämta handläggning
      description: Hämta handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Handläggning hämtat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)
    put:
      tags: [ HandlaggningController ]
      operationId: putHandlaggning
      summary: Uppdatera handläggning
      description: Uppdatera handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutHandlaggningRequest'
      responses:
        '200':
          description: Handläggning uppdaterad OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)

components:
  schemas:

    GetHandlaggningResponse:
      type: object
      description: Svar vid hämtning av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    PutHandlaggningRequest:
      type: object
      description: Uppdatera handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/HandlaggningUpdate'
      required:
        - handlaggning

    PutHandlaggningResponse:
      type: object
      description: Svar vid uppdatering av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/HandlaggningUpdate'
      required:
        - handlaggning

    Yrkande:
      type: object
      description: Yrkande
      properties:
        id:
          type: string
          description: Yrkandets unika ID
          format: uuid
        version:
          type: integer
          description: Yrkandets version
        erbjudandeId:
          type: string
          description: Erbjudandets unika ID
        yrkandedatum:
          type: string
          description: Datetime när yrkandet uppstod, enligt ISO 8601
          format: date-time
        yrkandestatus:
          type: string
          description: Unikt ID som identifierar status för yrkandet
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        avsikt:
          type: string
          description: Unikt ID som identifierar avsikt för yrkandet
        individYrkandeRoller:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/IndividYrkandeRoll'
        produceradeResultat:
          type: array
          description: Lista av producerade resultat
          items:
            $ref: '#/components/schemas/ProduceratResultat'
        beslut:
            $ref: '#/components/schemas/Beslut'
      required:
        - id
        - version
        - erbjudandeId
        - yrkandedatum
        - yrkandestatus
        - yrkandeFrom
        - yrkandeTom
        - avsikt
        - individYrkandeRoller
        - produceradeResultat

    ProduceratResultat:
      type: object
      description: Producerat resultat
      properties:
        id:
          type: string
          format: uuid
          description: Producerade resultatets unika ID
        version:
          type: integer
          description: Version av producerat resultat
        from:
          type: string
          format: date-time
          description: Startdatum/tid då resultatet gäller från, enligt ISO 8601
        tom:
          type: string
          format: date-time
          description: Slutdatum/tid då resultatet gäller till, enligt ISO 8601
        yrkandestatus:
          type: string
          description: Unikt ID som identifierar status för resultat
        avslagsanledning:
          type: string
          description: Orsak till avslag
          nullable: true
        typ:
          type: string
          description: Specificerar vilket typ av resultat objekt
        data:
          type: string
          description: Json data av den typ som har angetts
      required:
        - id
        - version
        - from
        - tom
        - yrkandestatus
        - typ
        - data
      example:
        id: "b0faa3ef-2728-4448-9984-c53e8e0f4c65"
        version: 1
        from: "2025-01-01T00:00:00Z"
        tom: "2025-01-02T00:00:00Z"
        yrkandestatus: "bd6320bc-2431-4f60-862e-e9f0cead28ce"
        avslaganledning: "Krav ej uppfyllda"
        typ: "ERSATTNING"
        data: "{}"

    HandlaggningUpdate:
      type: object
      description: Uppdaterbar handläggning, ärendeinstans
      properties:
        id:
          type: string
          description: Handläggningens unika ID
          format: uuid
        version:
          type: integer
          description: Handläggningens version
        yrkande:
          $ref: '#/components/schemas/Yrkande'
        processinstansId:
          type: string
          description: BPMN processinstansens unika ID
          format: uuid
          nullable: true
        skapadTS:
          type: string
          description: DateTime när handläggning skapades, enligt ISO 8601
          format: date-time
        avslutadTS:
          type: string
          description: DateTime när handläggning avslutades, enligt ISO 8601
          format: date-time
          nullable: true
        handlaggningspecifikationId:
          type: string
          format: uuid
        underlag:
          type: array
          description: Ett eller flera underlag som handläggningen använder sig av
          items:
            $ref: '#/components/schemas/Underlag'
        uppgift:
          $ref: '#/components/schemas/Uppgift'
          nullable: true
      required:
        - id
        - version
        - yrkande
        - skapadTS
        - handlaggningspecifikationId
        - underlag

    Handlaggning:
      type: object
      description: Handläggning, ärendeinstans
      properties:
        id:
          type: string
          description: Handläggningens unika ID
          format: uuid
        version:
          type: integer
          description: Handläggningens version
        yrkande:
          $ref: '#/components/schemas/Yrkande'
        processinstansId:
          type: string
          description: BPMN processinstansens unika ID
          format: uuid
          nullable: true
        skapadTS:
          type: string
          description: DateTime när handläggning skapades, enligt ISO 8601
          format: date-time
        avslutadTS:
          type: string
          description: DateTime när handläggning avslutades, enligt ISO 8601
          format: date-time
          nullable: true
        handlaggningspecifikationId:
          type: string
          format: uuid
      required:
        - id
        - version
        - yrkande
        - skapadTS
        - handlaggningspecifikationId

    Uppgift:
      type: object
      description: Uppgift
      properties:
        id:
          type: string
          description: Uppgiftens ID
          format: uuid
        version:
          type: integer
          description: Uppgiftens version
        skapadTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften skapades, enligt ISO 8601
        utfordTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften utfördes, enligt ISO 8601
          nullable: true
        planeradTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften är planerad att utföras, enligt ISO 8601
          nullable: true
        utforarId:
          $ref: '#/components/schemas/Idtyp'
          description: Utförarens ID
          nullable: true
        aktivitetId:
          type: string
          description: Aktivitetens Id
          format: uuid
        uppgiftspecifikation:
          $ref: '#/components/schemas/UppgiftSpecifikation'
        uppgiftStatus:
          type: string
          description: Unikt ID som identifierar status för uppgift
          nullable: true
        FSSAinformation:
          type: string
          description: Unikt ID som identifierar FSSÄ-information
      required:
        - id
        - version
        - skapadTs
        - uppgiftspecifikation
        - aktivitetId
        - FSSAinformation

    UppgiftSpecifikation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        version:
          type: integer
      required:
        - id
        - version

    Underlag:
      type: object
      properties:
        typ:
          type: string
          description: Specificerar vilken typ av underlag det är
        version:
          type: integer
          description: Specificerar vilken version av underlags typ det är
        data:
          type: string
          description: All data i underlaget i formatet JSON
      required:
        - typ
        - version
        - data

    IndividYrkandeRoll:
      type: object
      description: Representerar en individ tillsammans med dess roll
      properties:
        individ:
          $ref: '#/components/schemas/Idtyp'
          description: Unikt id till en individ
        yrkandeRollId:
          type: string
          description: Unikt id till en yrkande roll
      required:
        - individ
        - yrkandeRollId

    Beslut:
      type: object
      description: Beslut för yrkandet
      nullable: true
      properties:
        id:
          type: string
          format: uuid
          description: Unikt ID för beslut
        version:
          type: integer
          description: Specificerar version av beslutet
        datum:
          type: string
          format: date-time
          description: Tidpunkt för beslutet, enligt ISO 8601
        beslutsfattare:
          $ref: '#/components/schemas/Idtyp'
          description: Beslutsfattarens individ-id
        beslutsrader:
          type: array
          items:
            $ref: '#/components/schemas/Beslutsrad'
      required:
        - id
        - version
        - datum
        - beslutsfattare
        - beslutsrader

    Beslutsrad:
      type: object
      description: En beslutsrad i ett beslut
      properties:
        id:
          type: string
          format: uuid
          description: Unikt ID för beslutsrad
        version:
          type: integer
          description: Specificerar version av beslutsrad
        beslutsTyp:
          type: string
          description: Unikt ID som identfierar typ av beslut för beslutsrad
        beslutsUtfall:
          type: string
          description: Unikt ID som identifierar utfall för beslutsrad
        avslutsTyp:
          type: string
          description: Unikt ID som idenfierar typ av avslut för beslutsrad
        produceradeResultatRef:
          type: array
          description: Producerade resultat som beslutsraden är kopplat till
          items:
            $ref: '#/components/schemas/ProduceratResultatRef'
      required:
        - id
        - version
        - beslutsTyp
        - beslutsUtfall
        - avslutsTyp
        - produceradeResultatRef

    ProduceratResultatRef:
      type: object
      description: Referens till ett producerat resultat
      properties:
        id:
          type: string
          format: uuid
          description: Unikt ID för producerat resultat
        version:
          type: integer
          description: Specificerar version av producerade resultatet
      required:
        - id
        - version

    Idtyp:
      type: object
      properties:
        typId:
          type: string
          description: Unikt ID som identifierar vilken typ av värde som anges
        varde:
            type: string
            description: ID-värde som identifieras av typ
      required:
        - typId
        - varde
      example:
        typId: "4c34906c-03d9-425f-9a1a-062ef6eb88c7"
        varde: "19901010-1234"
