openapi: 3.0.3
info:
  title: Handläggning API
  version: 1.0.0
  description: API för att hantera handläggningar och yrkanden.

paths:
  /yrkande:
    post:
      tags: [ HandlaggningController ]
      operationId: postYrkande
      summary: Skapar ett nytt yrkande
      description: Skapar ett nytt yrkande
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostYrkandeRequest'
      responses:
        '201':
          description: Skapat yrkande OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostYrkandeResponse'

  /handlaggning:
    post:
      tags: [ HandlaggningController ]
      operationId: postHandlaggning
      summary: Skapa en ny handläggning
      description: Skapa en ny handläggning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostHandlaggningRequest'
      responses:
        '201':
          description: Handläggning skapat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt yrkande)

  /handlaggning/{handlaggningId}:
    get:
      tags: [ HandlaggningController ]
      operationId: getHandlaggning
      summary: Hämta handläggning
      description: Hämta handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Handläggning hämtat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)
    put:
      tags: [ HandlaggningController ]
      operationId: putHandlaggning
      summary: Uppdatera handläggning
      description: Uppdatera handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutHandlaggningRequest'
      responses:
        '200':
          description: Handläggning uppdaterad OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)

components:
  schemas:

    PostYrkandeRequest:
      type: object
      description: Data som krävs för att skapa ett nytt yrkande
      properties:
        erbjudandeId:
          type: string
          format: uuid
          description: Vilket erbjudande yrkandet avser
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        individYrkandeRoller:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/IndividYrkandeRoll'
        produceradeResultat:
          type: array
          description: Lista av producerade resultat
          items:
            $ref: '#/components/schemas/ProduceratResultat'
      required:
        - erbjudandeId
        - yrkandeFrom
        - yrkandeTom
        - individYrkandeRoller
        - produceradeResultat
      example:
        erbjudandeId: "a3b9c7b8-1234-4567-89ab-123456789abc"
        yrkandeFrom: "2025-01-01T00:00:00Z"
        yrkandeTom: "2025-01-02T00:00:00Z"
        individYrkandeRoller:
          - individId: "58435904-c2b6-4b1f-a0ab-62f1839d8ff2"
            yrkandeRollId: "58435904-c2b6-4b1f-a0ab-62f1839d8ff2"
        produceradeResultat:
          - from: "2025-01-01T00:00:00Z"
            tom: "2025-01-02T00:00:00Z"
            typ: "ERSATTNING"
            data: "{}"

    PostYrkandeResponse:
      type: object
      description: Svar vid skapande av ett nytt yrkande
      properties:
        yrkande:
          $ref: '#/components/schemas/Yrkande'
      required:
        - yrkande

    GetHandlaggningResponse:
      type: object
      description: Svar vid skapande/hämtning av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    PostHandlaggningRequest:
      type: object
      description: Skapa ny handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'

    PostHandlaggningResponse:
      type: object
      description: Svar vid skapande av ny handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning


    PutHandlaggningRequest:
      type: object
      description: Uppdatera handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'

    PutHandlaggningResponse:
      type: object
      description: Svar vid uppdatering av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    Yrkande:
      type: object
      description: Yrkande
      properties:
        id:
          type: string
          description: Yrkandets unika ID
          format: uuid
        version:
          type: integer
          description: Yrkandets version
        erbjudandeId:
          type: string
          description: Erbjudandets unika ID
          format: uuid
        yrkandedatum:
          type: string
          description: Datetime när yrkandet uppstod, enligt ISO 8601
          format: date-time
        yrkandestatus:
          $ref: '#/components/schemas/Yrkandestatus'
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        avsikt:
          $ref: '#/components/schemas/Avsiktstyp'
        individYrkandeRoller:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/IndividYrkandeRoll'
        produceradeResultat:
          type: array
          description: Lista av producerade resultat
          items:
            $ref: '#/components/schemas/ProduceratResultat'
      required:
        - id
        - version
        - erbjudandeId
        - yrkandedatum
        - yrkandestatus
        - yrkandeFrom
        - yrkandeTom
        - avsikt
        - individYrkandeRoller
        - produceradeResultat

    Yrkandestatus:
      type: string
      description: Yrkandestatus
      enum:
        - PLANERAT
        - YRKAT
        - UNDER_UTREDNING
        - FASTSTALLT_UNDER_UTREDNING
        - FASTSTALLT

    Avsiktstyp:
      type: string
      description: Avsiktstyp
      enum:
        - NY
        - ANDRING
        - BORTTAG
        - ATERTAGEN

    ProduceratResultat:
      type: object
      description: Producerat resultat
      properties:
        id:
          type: string
          format: uuid
          description: Producerade resultatets unika ID
        version:
          type: integer
          description: Version av producerat resultat
        from:
          type: string
          format: date-time
          description: Startdatum/tid då resultatet gäller från, enligt ISO 8601
        tom:
          type: string
          format: date-time
          description: Slutdatum/tid då resultatet gäller till, enligt ISO 8601
        typ:
          type: string
          description: Specificerar vilket typ av resultat objekt
        data:
          type: string
          description: Json data av den typ som har angetts
      required:
        - id
        - version
        - from
        - tom
        - typ
        - data

    Handlaggning:
      type: object
      description: Handläggning, ärendeinstans
      properties:
        id:
          type: string
          description: Handläggningens unika ID
          format: uuid
        version:
          type: string
          description: Handläggningens version
        yrkande:
          $ref: '#/components/schemas/Yrkande'
        processinstansId:
          type: string
          description: BPMN processinstansens unika ID
          format: uuid
        skapadTS:
          type: string
          description: DateTime när handläggning skapades, enligt ISO 8601
          format: date-time
        avslutadTS:
          type: string
          description: DateTime när handläggning avslutades, enligt ISO 8601
          format: date-time
        handlaggningspecifikationId:
          type: string
          format: uuid
        underlag:
          type: array
          description: Ett eller flera underlag som handläggningen använder sig av
          items:
            $ref: '#/components/schemas/Underlag'
        uppgift:
          $ref: '#/components/schemas/Uppgift'
      required:
        - id
        - version
        - yrkande
        - processinstansId
        - skapadTS
        - handlaggningspecifikationId
        - underlag

    UppgiftStatus:
      type: string
      description: Uppgiftens status
      enum:
        - PLANERAD
        - TILLDELAD
        - AVSLUTAD

    Uppgift:
      type: object
      description: Uppgift
      properties:
        id:
          type: string
          description: Uppgiftens ID
          format: uuid
        version:
          type: string
          description: Uppgiftens version
        skapadTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften skapades, enligt ISO 8601
        utfordTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften utfördes, enligt ISO 8601
          nullable: true
        planeradTs:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften är planerad att utföras, enligt ISO 8601
          nullable: true
        utforarId:
          type: string
          description: Utförarens ID
          format: uuid
          nullable: true
        aktivitetId:
          type: string
          description: Aktivitetens Id
          format: uuid
        uppgiftspecifikation:
          $ref: '#/components/schemas/UppgiftSpecifikation'
        uppgiftStatus:
          $ref: '#/components/schemas/UppgiftStatus'
        FSSAinformation:
          $ref: '#/components/schemas/FSSAinformation'

      required:
        - id
        - version
        - handlaggningId
        - uppgiftStatus

    UppgiftSpecifikation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        version:
          type: int

      required:
        - id
        - version
        - handlaggningId
        - uppgiftStatus

    Underlag:
      type: object
      properties:
        typ:
          type: string
          description: Specificerar vilken typ av underlag det är
        version:
          type: string
          description: Specificerar vilken version av underlags typ det är
        data:
          type: string
          description: All data i underlaget i formatet JSON
      required:
        - typ
        - version
        - data

    Resultat:
      type: object
      properties:
        id:
          type: string
          description: Resultatets unika id
          format: uuid
        version:
          type: string
          description: Specificerar vilken version av resultatet det är
        from:
          type: string
          format: date-time
          description: Resultat från och med datum
        tom:
          type: string
          format: date-time
          description: Resultat till och med datum
        yrkandestatus:
          $ref: '#/components/schemas/Yrkandestatus'
        avslagsanledning:
          type: string
          description: Orsak till avslag
        typ:
          type: string
          description: Specificerar vilken typ av resultat det är
        data:
          type: string
          description: All data i resultatet i formatet JSON
      required:
        - id
        - version
        - from
        - tom
        - yrkandestatus
        - typ
        - data

    FSSAinformation:
      type: string
      enum:
        - HANDLAGGNING_PAGAR
        - VANTAR_PA_INFO_FRAN_ANNAN_PART
        - VANTAR_PA_INFO_FRAN_KUND




    IndividYrkandeRoll:
      type: object
      description: Representerar en individ tillsammans med dess roll
      properties:
        individId:
          type: string
          format: uuid
          description: Id till en individ
        yrkandeRollId:
          type: string
          format: uuid
          description: Id till en yrkande roll
      required:
        - individId
        - yrkandeRollId

    Beslutsutfall:
      type: string
      description: Beslutsutfall för ersättning
      enum:
        - JA
        - NEJ
        - FU

