openapi: 3.1.0
info:
  title: Handläggning API
  version: 1.0.0
  description: API för att hantera handläggningar och yrkanden.

paths:
  /handlaggning/{handlaggningId}:
    get:
      tags: [ HandlaggningController ]
      operationId: getHandlaggning
      summary: Hämta handläggning
      description: Hämta handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Handläggning hämtat OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHandlaggningResponse'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)
    put:
      tags: [ HandlaggningController ]
      operationId: putHandlaggning
      summary: Uppdatera handläggning
      description: Uppdatera handläggning knutet till handlaggningId
      parameters:
        - name: handlaggningId
          in: path
          required: true
          description: Handläggningens id
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HandlaggningUpdate'
      responses:
        '200':
          description: Handläggning uppdaterad OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HandlaggningUpdate'
        '400':
          description: Bad request (t.ex. felaktigt handlaggningId)
        '409':
          description: Conflict (t.ex. version av objekt har inte steppats vid ändring)

components:
  schemas:

    GetHandlaggningResponse:
      type: object
      description: Svar vid hämtning av handläggning
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
      required:
        - handlaggning

    Yrkande:
      type: object
      description: Yrkande
      properties:
        id:
          type: string
          description: Yrkandets unika ID
          format: uuid
        version:
          type: integer
          description: Yrkandets version
        ingangtypId:
          type: string
          description: Ingångtypens unika ID
        yrkandedatum:
          type: string
          description: Datetime när yrkandet uppstod, enligt ISO 8601
          format: date-time
        yrkandestatus:
          type: string
          description: Unikt ID som identifierar status för yrkandet
        yrkandeFrom:
          type: string
          format: date-time
          description: Yrkande från och med datum
        yrkandeTom:
          type: string
          format: date-time
          description: Yrkande till och med datum
        avsikt:
          type: string
          description: Unikt ID som identifierar avsikt för yrkandet
        rollerIYrkande:
          type: array
          description: Lista av personer involverade i yrkandet samt deras roll
          items:
            $ref: '#/components/schemas/RollIYrkande'
        sakfragorStallningstaganden:
          type: array
          description: Lista av sakfrågor och ställningstaganden i yrkandet
          items:
            $ref: '#/components/schemas/SakfragaStallningstagandeContainer'
        beslut:
          type: array
          description: Lista av beslut
          items:
            $ref: '#/components/schemas/Beslut'
      required:
        - id
        - version
        - ingangtypId
        - yrkandedatum
        - yrkandestatus
        - yrkandeFrom
        - yrkandeTom
        - avsikt
        - rollerIYrkande
        - sakfragorStallningstaganden
        - beslut

    SakfragaStallningstagandeContainer:
      type: object
      description: Container för sakfråga eller ställningstagande
      properties:
        id:
          type: string
          format: uuid
          description: Unikt id
        objektTypId:
          type: string
          description: Unikt ID som identifierar vilken typ av sakfråga/ställningstagande det gäller
        data:
          type: string
          description: Json data av den typ som objektTypId avser
      required:
        - id
        - objektTypId
        - data

    HandlaggningUpdate:
      type: object
      description: Uppdaterbar handläggning, ärendeinstans
      properties:
        handlaggning:
          $ref: '#/components/schemas/Handlaggning'
        uppgift:
          $ref: '#/components/schemas/Uppgift'
      required:
        - handlaggning
        - uppgift

    Handlaggning:
      type: object
      description: Handläggning, ärendeinstans
      properties:
        id:
          type: string
          description: Handläggningens unika ID
          format: uuid
        version:
          type: integer
          description: Handläggningens version
        yrkande:
          $ref: '#/components/schemas/Yrkande'
        handlaggningIdTyp:
          type: string
          description: Unikt ID som identifierar handläggningstyp
        handlaggningIdVarde:
          type: [ string, 'null' ]
          description: Handläggningens Id värde
        skapadTS:
          type: string
          description: DateTime när handläggning skapades, enligt ISO 8601
          format: date-time
        avslutadTS:
          type: [ string, 'null' ]
          description: DateTime när handläggning avslutades, enligt ISO 8601
          format: date-time
        handlaggningspecifikationId:
          type: string
          format: uuid
      required:
        - id
        - version
        - yrkande
        - skapadTS
        - handlaggningspecifikationId
        - handlaggningIdTyp

    Uppgift:
      type: object
      description: Uppgift
      properties:
        id:
          type: string
          description: Uppgiftens ID
          format: uuid
        version:
          type: integer
          description: Uppgiftens version
        skapadTS:
          type: string
          format: date-time
          description: Tidpunkt då uppgiften skapades, enligt ISO 8601
        utfordTS:
          type: [ string, 'null' ]
          format: date-time
          description: Tidpunkt då uppgiften utfördes, enligt ISO 8601
        planeradTillTS:
          type: [ string, 'null' ]
          format: date-time
          description: Tidpunkt då uppgiften är planerad att utföras, enligt ISO 8601
        utforare:
          description: Utförarens ID
          anyOf:
            - $ref: '#/components/schemas/Idtyp'
            - type: 'null'
        aktivitetId:
          type: string
          description: Aktivitetens Id
          format: uuid
        uppgiftspecifikation:
          $ref: '#/components/schemas/UppgiftSpecifikation'
        uppgiftStatus:
          type: [ string, 'null' ]
          description: Unikt ID som identifierar status för uppgift
        kommentar:
          type: [ string, 'null' ]
          description: Kommentar gällande uppgiften
        FSSAinformation:
          type: string
          description: Unikt ID som identifierar FSSÄ-information
        regelutfall:
          anyOf:
            - $ref: '#/components/schemas/Regelutfall'
            - type: 'null'
        handlaggningId:
          type: string
          format: uuid
          description: Unikt ID som identifierar handläggningen
        underlag:
          type: array
          description: Ett eller flera underlag som uppgiften använder sig av
          items:
            $ref: '#/components/schemas/Underlag'
        resultat:
          type: array
          description: Ett eller flera resultat som uppgiften producerat
          items:
            $ref: '#/components/schemas/Uppgiftsdata'
      required:
        - id
        - version
        - skapadTS
        - uppgiftspecifikation
        - aktivitetId
        - FSSAinformation
        - handlaggningId

    Regelutfall:
      type: object
      properties:
        varde:
          type: string
          description: Värde av regelutfall
      required:
        - varde

    UppgiftSpecifikation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        version:
          type: integer
      required:
        - id
        - version

    Uppgiftsdata:
      type: object
      properties:
        informationsobjektId:
          type: string
          description: Unikt ID som identifierar ett informationsobjekt
        version:
          type: integer
          description: Specificerar vilken version av informationsobjekt det är
      required:
        - informationsobjektId
        - version

    Underlag:
      type: object
      properties:
        typ:
          type: string
          description: Specificerar vilken typ av underlag det är
        version:
          type: integer
          description: Specificerar vilken version av underlags typ det är
        data:
          type: string
          description: All data i underlaget i formatet JSON
      required:
        - typ
        - version
        - data

    RollIYrkande:
      type: object
      description: Representerar en individ tillsammans med dess roll
      properties:
        id:
          type: string
          format: uuid
          description: Unikt id för denna individ och roll kopplat till ett yrkande
        individ:
          $ref: '#/components/schemas/Idtyp'
          description: Unikt id till en individ
        yrkandeRollId:
          type: string
          description: Unikt id till en yrkande roll
        avserYrkande:
          type: string
          format: uuid
          description: Unikt id som identifierar vilket yrkande denna RollIYrkande avser
      required:
        - id
        - individ
        - yrkandeRollId
        - avserYrkande

    Beslut:
      type: object
      description: Beslut för yrkandet
      properties:
        id:
          type: string
          format: uuid
          description: Unikt ID för beslut
        version:
          type: integer
          description: Specificerar version av beslutet
        datum:
          type: string
          format: date-time
          description: Tidpunkt för beslutet, enligt ISO 8601
        beslutsfattare:
          $ref: '#/components/schemas/Idtyp'
          description: Beslutsfattarens individ-id
        beslutsrader:
          type: array
          items:
            $ref: '#/components/schemas/Beslutsrad'
      required:
        - id
        - version
        - datum
        - beslutsfattare
        - beslutsrader

    Beslutsrad:
      type: object
      description: En beslutsrad i ett beslut
      properties:
        id:
          type: string
          format: uuid
          description: Unikt ID för beslutsrad
        version:
          type: integer
          description: Specificerar version av beslutsrad
        beslutsTyp:
          type: string
          description: Unikt ID som identfierar typ av beslut för beslutsrad
        beslutsUtfall:
          type: string
          description: Unikt ID som identifierar utfall för beslutsrad
        avslutsTyp:
          type: string
          description: Unikt ID som idenfierar typ av avslut för beslutsrad
        sakfragorStallningstaganden:
          type: array
          description: Lista av ID och version som identifierar SakfragaStallningstagande
          items:
            $ref: '#/components/schemas/SakfragaStallningstagandeRef'
      required:
        - id
        - version
        - beslutsTyp
        - beslutsUtfall
        - avslutsTyp
        - sakfragorStallningstaganden

    SakfragaStallningstagandeRef:
      type: object
      description: Referens till en sakfråga eller ställningstagande
      properties:
        id:
          type: string
          format: uuid
          description: Unikt ID för sakfrågan eller ställningstagande
        version:
          type: integer
          description: Specificerar version av sakfrågan eller ställningstagande
      required:
        - id
        - version

    Idtyp:
      type: object
      properties:
        typId:
          type: string
          description: Unikt ID som identifierar vilken typ av värde som anges
        varde:
          type: string
          description: ID-värde som identifieras av typ
      required:
        - typId
        - varde
      examples:
        - typId: "4c34906c-03d9-425f-9a1a-062ef6eb88c7"
          varde: "19901010-1234"
